# Generated by Django 3.1.5 on 2021-02-09 11:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Authentication.user')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('user_image', models.ImageField(null=True, upload_to='user_photo')),
                ('user_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'db_table': 'tbl_profile_mst',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('state_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_states',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('acc_no', models.CharField(max_length=20)),
                ('acc_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('IFSC_code', models.CharField(max_length=11)),
                ('pan_no', models.CharField(max_length=10)),
                ('pan_name', models.CharField(max_length=25)),
                ('pan_img_url', models.ImageField(null=True, upload_to='doc_photo')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_documents',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('city_name', models.CharField(max_length=30)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.states')),
            ],
            options={
                'db_table': 'tbl_cities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('person_name', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('line1', models.TextField(max_length=100)),
                ('line2', models.TextField(max_length=100)),
                ('landmark', models.TextField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=6)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.cities')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Authentication.states')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_address',
            },
        ),
    ]
