# Generated by Django 3.1.4 on 2021-02-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Authentication.user')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('user_image', models.ImageField(null=True, upload_to='user_photo')),
                ('user_mobile', models.CharField(max_length=10, unique=True)),
                ('user_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
