# Generated by Django 3.1.4 on 2021-02-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_mobile',
        ),
    ]
