# Generated by Django 3.1.4 on 2021-02-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cities',
            old_name='state_id',
            new_name='state',
        ),
    ]
