# Generated by Django 3.1.4 on 2021-02-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_profile_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
