# Generated by Django 3.1.4 on 2021-02-09 04:37

import Authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20210207_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.FileField(null=True, upload_to=Authentication.models.user_photo, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
