# Generated by Django 3.1.4 on 2021-02-09 05:02

import Authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20210209_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(null=True, upload_to=Authentication.models.user_photo),
        ),
    ]
