# Generated by Django 3.1.4 on 2021-02-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20210212_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='bank_name',
            field=models.IntegerField(choices=[(1, 'State Bank of India'), (2, 'Bank of Baroda'), (3, 'ICICI Bank'), (4, 'HDFC Bank'), (5, 'Bank of India'), (6, 'Axis Bank')]),
        ),
    ]
