# Generated by Django 3.1.4 on 2021-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_auto_20210212_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='bank_name',
            field=models.IntegerField(),
        ),
    ]
