# Generated by Django 3.1.4 on 2021-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_auto_20210212_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
    ]
