# Generated by Django 3.1.4 on 2021-02-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_auto_20210210_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='default1', max_length=200),
        ),
    ]
