# Generated by Django 3.1.4 on 2021-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_auto_20210212_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
