# Generated by Django 3.1.4 on 2021-02-10 00:37

import Authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_auto_20210210_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default=None, null=True, upload_to=Authentication.models.user_photo),
        ),
    ]
