# Generated by Django 3.1.5 on 2021-03-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_auto_20210222_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True),
        ),
    ]
