# Generated by Django 3.1.4 on 2021-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=256)),
                ('query_subject', models.CharField(max_length=50)),
                ('query_message', models.CharField(max_length=500, null=True)),
                ('query_status', models.CharField(default='Pending', max_length=80)),
                ('query_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
