# Generated by Django 3.0.5 on 2021-01-27 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_orders_details',
            fields=[
                ('order_details_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('crt_item_qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('pickup_address', models.CharField(max_length=350)),
                ('item_status', models.CharField(choices=[('PLACED', 'Placed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_orders_mst',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('person_name', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
                ('delivery_address', models.CharField(max_length=350)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=15)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
