# Generated by Django 3.1.5 on 2021-02-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20210207_2101'),
        ('Order', '0002_auto_20210207_1913'),
    ]

    operations = [
    ]
