# Generated by Django 3.1.4 on 2021-03-02 15:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0002_auto_20210220_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_orders_mst',
            name='order_status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_orders_mst',
            name='user_id',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.RESTRICT, to='Authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_orders_details',
            name='item_status',
            field=models.PositiveIntegerField(choices=[(1, 'Placed'), (2, 'Completed'), (3, 'Cancelled'), (4, 'Failed'), (5, 'Returned')]),
        ),
        migrations.AlterField(
            model_name='tbl_orders_details',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='tbl_orders_mst',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tbl_orders_mst',
            name='delivery_status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Dispatched'), (3, 'Delivered'), (4, 'Cancelled')]),
        ),
        migrations.AlterField(
            model_name='tbl_orders_mst',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
