# Generated by Django 3.1.4 on 2021-03-02 18:16

import Order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20210302_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_orders_mst',
            name='delivery_date',
            field=models.DateTimeField(default=Order.models.getDeliveryDate),
        ),
        migrations.AlterField(
            model_name='tbl_orders_mst',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
