# Generated by Django 3.1.4 on 2021-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20210302_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_orders_mst',
            name='delivery_address',
            field=models.TextField(max_length=350),
        ),
    ]
