# Generated by Django 3.1.4 on 2021-03-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20210302_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_orders_details',
            old_name='crt_item_details',
            new_name='crt_item_mst',
        ),
        migrations.AlterField(
            model_name='tbl_orders_details',
            name='item_status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Cancelled'), (4, 'Failed'), (5, 'Returned')]),
        ),
    ]
