# Generated by Django 3.1.4 on 2021-03-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_auto_20210303_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_orders_details',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.tbl_orders_mst'),
        ),
    ]
