# Generated by Django 3.1.4 on 2021-03-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20210303_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_orders_mst',
            old_name='user_id',
            new_name='user',
        ),
    ]
