# Generated by Django 3.1.4 on 2021-01-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='MainCreativeCategory',
        ),
    ]
