# Generated by Django 3.1.4 on 2021-02-20 16:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_creativeitems_details',
            name='crt_item',
        ),
        migrations.AddField(
            model_name='tbl_creativeitems_mst',
            name='crt_item_SKU',
            field=models.CharField(default='aa', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_creativeitems_mst',
            name='crt_item_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_creativeitems_mst',
            name='crt_item_qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_creativeitems_mst',
            name='crt_item_status',
            field=models.CharField(choices=[('INAPPROPRIATE', 'Inappropriate'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLD', 'Sold')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='tbl_creativeitems_mst',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, to='Authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_creativeitems_mst',
            name='crt_item_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_creativeitems_mst',
            name='crt_item_width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_crtimages',
            name='crt_item_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.tbl_creativeitems_mst'),
        ),
    ]
