# Generated by Django 3.1.4 on 2021-01-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20210120_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincreativecategory',
            old_name='name',
            new_name='crt_category_name',
        ),
    ]
