# Generated by Django 3.1.4 on 2021-02-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20210220_2146'),
        ('Items', '0002_auto_20210220_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_creativeitems_details',
        ),
    ]
