# Generated by Django 3.1.4 on 2021-01-20 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_auto_20210120_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincreativecategory',
            name='id',
        ),
        migrations.AddField(
            model_name='maincreativecategory',
            name='crt_category_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)]),
            preserve_default=False,
        ),
    ]
