# Generated by Django 3.1.4 on 2021-02-18 10:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0004_auto_20210215_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('issue_type', models.PositiveIntegerField(choices=[(1, 'Reported Creative Items'), (2, 'Reported Scrap Items'), (3, 'Reported Users Items')])),
                ('issue_sub', models.PositiveIntegerField(choices=[(1, "Doesn't match product"), (2, 'Missing/Incorrect information'), (3, 'Offensive or adult content'), (4, 'Is not clear'), (5, 'Other')])),
                ('issue_msg', models.TextField(blank=True, max_length=100, null=True)),
                ('issue_status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Resolved'), (3, 'Rejected')], default='Pending')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('crt_item_id', models.PositiveIntegerField(null=True)),
                ('reported_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reportee', to=settings.AUTH_USER_MODEL)),
                ('scp_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Items.tbl_scrapitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_issues',
            },
        ),
    ]
