# Generated by Django 3.1.4 on 2021-01-20 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_auto_20210120_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCreativeCategory',
            fields=[
                ('crt_sub_category_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('crt_sub_category_name', models.CharField(max_length=40)),
                ('crt_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.maincreativecategory')),
            ],
        ),
    ]
