# Generated by Django 3.1.4 on 2021-02-22 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0005_auto_20210222_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scrapitems',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
