# Generated by Django 3.1.4 on 2021-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_issues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='reported_user_id',
            new_name='reported_user',
        ),
        migrations.AlterField(
            model_name='issues',
            name='issue_status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Resolved'), (3, 'Rejected')], default=1),
        ),
    ]
