# Generated by Django 3.1.4 on 2021-01-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_subcreativecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcreativecategory',
            name='crt_category_id',
        ),
        migrations.DeleteModel(
            name='MainCreativeCategory',
        ),
        migrations.DeleteModel(
            name='SubCreativeCategory',
        ),
    ]
