# Generated by Django 3.1.4 on 2021-02-23 18:55

import Items.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0006_auto_20210222_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scrapimages',
            name='scp_img_url',
            field=models.ImageField(max_length=150, null=True, upload_to=Items.models.scp_product_photo, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
