# Generated by Django 3.1.5 on 2021-03-06 15:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0007_auto_20210224_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('item_rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True)),
                ('item_review', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(auto_now=True)),
                ('crt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.tbl_creativeitems_mst')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
