# Generated by Django 3.1.4 on 2021-02-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0007_auto_20210218_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='scp_item',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
