# Generated by Django 3.1.4 on 2021-03-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_auto_20210310_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='crt_item_id',
            new_name='crt_item',
        ),
    ]
