# Generated by Django 3.1.4 on 2021-03-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0009_auto_20210310_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_scrapitems',
            name='username',
        ),
    ]
