# Generated by Django 3.1.4 on 2021-02-18 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0009_auto_20210218_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='crt_item',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reportee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issues',
            name='scp_item',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
