# Generated by Django 3.1.4 on 2021-03-11 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0010_remove_tbl_scrapitems_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scrapitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
