# Generated by Django 3.1.4 on 2021-03-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_reviews'),
        ('Items', '0013_auto_20210311_2219'),
    ]

    operations = [
    ]
