# Generated by Django 3.1.4 on 2021-03-22 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0014_merge_20210313_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scrapitems',
            name='username',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
