# Generated by Django 3.1.5 on 2021-01-31 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainScrapCategory',
            fields=[
                ('scp_category_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('scp_category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_crt_categories',
            fields=[
                ('crt_category_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('crt_category_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tbl_crt_categories',
            },
        ),
        migrations.CreateModel(
            name='tbl_crt_subcategories',
            fields=[
                ('crt_sub_category_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('crt_sub_category_name', models.CharField(max_length=40)),
                ('crt_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAdmin.tbl_crt_categories')),
            ],
            options={
                'db_table': 'tbl_crt_subcategories',
            },
        ),
        migrations.CreateModel(
            name='SubScrapCategory',
            fields=[
                ('scp_sub_category_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('scp_sub_category_name', models.CharField(max_length=40)),
                ('scp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAdmin.mainscrapcategory')),
            ],
        ),
    ]
