# Generated by Django 3.1.4 on 2021-01-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcreativecategory',
            old_name='crt_category_id',
            new_name='crt_category',
        ),
    ]
