# Generated by Django 3.1.5 on 2021-02-18 13:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustomAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('badge_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_badges',
            },
        ),
        migrations.CreateModel(
            name='BadgeEntries',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAdmin.badges')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_badges_entries',
            },
        ),
    ]
