# Generated by Django 3.1.5 on 2021-02-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdmin', '0002_badgeentries_badges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgeentries',
            old_name='user_id',
            new_name='user',
        ),
    ]
