# Generated by Django 3.1.4 on 2021-01-21 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomAdmin', '0002_auto_20210120_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainScrapCategory',
            fields=[
                ('scp_category_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('scp_category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubScrapCategory',
            fields=[
                ('scp_sub_category_id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('scp_sub_category_name', models.CharField(max_length=40)),
                ('scp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomAdmin.mainscrapcategory')),
            ],
        ),
    ]
